# generated by `tre --completions fish`; regenerate with:
#   tre --completions fish > fish/completions/tre.fish
complete -c tre -s o -l out -d 'Scan: where to write the .tre. Build: which folder to build in' -r -F
complete -c tre -s s -l style -d 'Scan: how to draw the tree' -r -f -a "unicode\t'├── box-drawing characters, like `tree`'
ascii\t'|-- plain ASCII'
indent\t'two-space indentation only'"
complete -c tre -s L -l depth -d 'Scan: descend at most this many levels' -r
complete -c tre -s x -l exclude -d 'Scan: leave out names matching this glob (repeatable, comma-separated)' -r
complete -c tre -l color -d 'When to use color' -r -f -a "auto\t''
always\t''
never\t''"
complete -c tre -l completions -d 'Print shell completions (fish, bash, zsh, elvish, powershell)' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c tre -s n -l dry-run -d 'Build: show what would be created, write nothing'
complete -c tre -s i -l interactive -d 'Build: show the plan and ask before creating anything'
complete -c tre -s p -l print -d 'Scan: print the tree instead of writing a .tre'
complete -c tre -s f -l force -d 'Scan: replace the .tre if it already exists'
complete -c tre -s H -l hidden -d 'Scan: include dotfiles'
complete -c tre -s I -l no-ignore -d 'Scan: don\'t read .gitignore / .ignore files'
complete -c tre -s a -l all -d 'Scan: include everything - dotfiles, ignored files, node_modules, target, .git'
complete -c tre -l json -d 'Machine-readable output: the scanned tree, or the build plan'
complete -c tre -s q -l quiet -d 'Only print errors'
complete -c tre -l man -d 'Print the man page'
complete -c tre -s h -l help -d 'Print help (see more with \'--help\')'
complete -c tre -s V -l version -d 'Print version'

# fish-only: offer .tre files and folders first for the path argument
complete -c tre -n '__fish_is_first_arg' -f -a '(__fish_complete_suffix .tre; __fish_complete_directories)'
complete -c tre-take -f -a '(__fish_complete_suffix .tre)'
complete -c tre-take -w tre
complete -c tre-paste -w tre
